version: '3.5'

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: /
    restart: always
    ports:
      - "7000:80"
    depends_on:
      - db-server
    networks:
      - localdev
      - redis

  db-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Ares4421096
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
